# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  pipelines:
    - pipeline: db_ci   
      source: azure-pipelines   
      trigger: true  

pool:
  vmImage: 'windows-latest'

steps:
- task: SqlAzureDacpacDeployment@1
  inputs:
    azureSubscription: 'Azure for Students(8a625f6d-518c-4254-8e23-7c08e01e1d45)'
    AuthenticationType: 'connectionString'
    ConnectionString: '$(ConnectionString)'
    deployType: 'DacpacTask'
    DeploymentAction: 'Publish'
    DacpacFile: '$(Pipeline.Workspace)/drop/SqlServerDatabase.dacpac'
    IpDetectionMethod: 'AutoDetect'

